proj_dir: "/home/vagrant/RegioHeldenTest" # Absolute path to the puppet template files directory (No need to change it)
tz: "Europe/Berlin" # Timezone
user: "regioheld" # User to create
password: "derheld" # The user's password
project: "RegioHeldenTest" # Django project folder or the name when you run django-admin.py startproject <PROJECT_NAME>
domain_name: "regioheldentest.com" # Used in nginx, uwsgi and virtualenv directory
db_name: "regioheldentest" # Postsql database name to create
db_user: "regioheld" # Posgresql username to create
db_password: "regiohelden" # Posgresql password for the db_user
