# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 03:56
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django_iban.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=32)),
                ('last_name', models.CharField(db_index=True, max_length=32)),
                ('iban', django_iban.fields.IBANField(enforce_database_constraint=False, help_text='Up to 34 chars bank account number, depends on country.', max_length=34, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(accounts.models.get_sentinel_user), related_name='customers_added', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
